[package]
name = "wireguard-linux-applet"
version = "0.1.0"
authors = ["joaoofreitas <joaoofreitas00@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
systray = "0.4.0"
gtk= "0.8.1"

